### PR TITLE
Removed mkmf.log  and added in gitignore

### PR DESCRIPTION
**Pull request by prabodhmeshram**
Related to #16

### CODE REVIEW

**Comment by crawfoal** [comment]
Thank you Prabodh!

**Comment by crawfoal** [comment]
How did you find this repo? I have quite a few people that are actively looking for open source projects to contribute to but aren't Ruby devs. I've given them a few resources, but do you have any recommendations for them?

**Comment by prabodhmeshram** [comment]
Hey @crawfoal 
Well as your tag suggested `first-timers-only` . Just wanted to start my github open source journey. Although the issue was really minor. But I felt really great to contribute and thought I could help :smile: 
Well for devs who want to contribute can follow the below sites:
 

- [CodeTriage](https://www.codetriage.com) 
- [Up For Grabs](http://up-for-grabs.net/)

Good links to start with, Even googling a bit on this topic will give you great pointers. That's how I landed here.

Well I am not a Ruby Dev, but I did know few other languages, so its not big deal to pick up Ruby as well. If you have really basic tasks in ruby, maybe I can help in those as well. Of course I may take more time, but I can help in getting job done !
Happy to help :)

**Comment by crawfoal** [comment]
I was wondering how you came to this specific repo, since (to my knowledge) it's not on either of those two sites. But I just realized that you can search across all repos on Github to find issues with a specific label: https://github.com/search?q=label%3Afirst-timers-only&state=open&type=Issues

**Comment by prabodhmeshram** [comment]
Yes this was mentioned in one of the sites for how to filter issues based on labels. That led me here :smile:

**Pull request merged**
